
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oac"
description = "OAC"
version = "0.0.1"
requires-python = ">= 3.10"
readme = "README.md"
authors = [
    { name = "Dylan Evans", email = "dylan@dje.me" },
]

